---
- name: add grafana repo key
  apt_key:
    url: https://packages.grafana.com/gpg.key 

- name: add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: install grafana
  apt:
    name: grafana
    state: present

- name: Start Grafana
  service:
    name: grafana-server
    state: restarted